# Manage chat control features here
chat-control:
  # Set this to true to enable full functionality of this feature
  enable-functionality: true
  # The message you want to send if a player sends a rude message
  warn-message: '&cPlease do not bypass chat filter.'
  # The list of words you want to filter from chat
  blacklisted-words:
  - 'fuck'
  - 'dick'
  - 'retard'
  # Manage your friends features here
your-friends:
  # True if you want users to be notified when a friend joins/leaves the server.
  notify-on-join: true
  notify-on-leave: true
  # The sound to play to notify players.
  notification-sound: NOTE_PLING
  # True to display online friends when joining the server.
  show-friends: false
  # To display distinguishable scoreboards below players name.
  # <COLOUR>:<1-Enable/0-Disable> Usage: 'AQUA:0' To Disable.
  show-scoreboard: 'AQUA:1'
  # The amount of friends players can have.
  friend-limit: 30
  